# What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types
https://numpy.org/doc/stable/reference/ufuncs.html

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [2]:
# np.array
import numpy as np
import pandas as pd

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b = np.array([[1,2],[3,4],[5,6],[7,8]])
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.85459423, 0.49581266, 0.04534546, 0.92523761],
       [0.70358759, 0.68279226, 0.73896194, 0.78523682],
       [0.90151444, 0.27679683, 0.94851621, 0.80299715]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim number of dimension
a3.ndim

3

In [ ]:
# shape
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# size
print(a1.size)
a1

10


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int64


### Changing Datatype

In [ ]:
# astype
#a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations
#every item will multiplied by two
# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational item wise comparision ( > < == )
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations u aplly this on two arrays
# arithmetic (/ - +)
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [ ]:
#Randomly generated Arrray
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[40., 62., 18.],
       [ 9.,  4., 61.],
       [55., 19., 30.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1)    # min sum prod


62.0

In [ ]:
#To get the maximum item in each row  (min,prod,sum)
np.max(a1)
np.max(a1,axis=0)


array([55., 62., 61.])

In [ ]:
# mean/median/std/var
np.mean(a1,axis=1)

array([40.        , 24.66666667, 34.66666667])

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[-1]

9

In [ ]:
a2        #Vertical column horizontal row

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[2,1]

9

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[0,0,0]

0

In [ ]:
a3[0,1,0]

2

In [ ]:
a3[0,0,1]

1

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Slicing
a1[2:8:2]

array([2, 4, 6])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,3]

array([ 3,  7, 11])

In [ ]:
a2[1:,1:3]

### Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#What is Pandas

#Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

https://pandas.pydata.org/about/index.html

In [4]:
# string
country = ['India','Pakistan','USA','Nepal','Srilanka']

pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [6]:
# integers
runs = [13,24,56,78,100]

runs_ser = pd.Series(runs)
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [8]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index = subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [9]:
marks_series = pd.Series(marks,name='Your marks')
marks_series

0     67
1     57
2     89
3    100
Name: Your marks, dtype: int64

In [10]:
# size
marks_series.size

4

In [11]:
marks_series.dtype

dtype('int64')

# **Pandas as Dataframe**

In [12]:
# using lists
student_data = [
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,50,2]
]

pd.DataFrame(student_data,columns=['iq','marks','package'])

iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [13]:
# using read_csv
movies = pd.read_csv('/content/movies.csv')
movies

title_x     imdb_id  \
0                 Uri: The Surgical Strike   tt8291224   
1                            Battalion 609   tt9472208   
2     The Accidental Prime Minister (film)   tt6986710   
3                          Why Cheat India   tt8108208   
4                          Evening Shadows   tt6028796   
...                                    ...         ...   
1624                 Tera Mera Saath Rahen   tt0301250   
1625                  Yeh Zindagi Ka Safar   tt0298607   
1626                       Sabse Bada Sukh   tt0069204   
1627                                 Daaka  tt10833860   
1628                              Humsafar   tt2403201   

                                            poster_path  \
0     https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                   NaN   
2     https://upload.wikimedia.org/wikipedia/en/thum...   
3     https://upload.wikimedia.org/wikipedia/en/thum...   
4                                                   NaN   
...                                                 ...   
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...   
1625  https://upload.wikimedia.org/wikipedia/en/thum...   
1626                                                NaN   
1627  https://upload.wikimedia.org/wikipedia/en/thum...   
1628  https://upload.wikimedia.org/wikipedia/en/thum...   

                                              wiki_link  \
0     https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1           https://en.wikipedia.org/wiki/Battalion_609   
2     https://en.wikipedia.org/wiki/The_Accidental_P...   
3         https://en.wikipedia.org/wiki/Why_Cheat_India   
4         https://en.wikipedia.org/wiki/Evening_Shadows   
...                                                 ...   
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...   
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...   
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh   
1627                https://en.wikipedia.org/wiki/Daaka   
1628             https://en.wikipedia.org/wiki/Humsafar   

                            title_y                 original_title  is_adult  \
0          Uri: The Surgical Strike       Uri: The Surgical Strike         0   
1                     Battalion 609                  Battalion 609         0   
2     The Accidental Prime Minister  The Accidental Prime Minister         0   
3                   Why Cheat India                Why Cheat India         0   
4                   Evening Shadows                Evening Shadows         0   
...                             ...                            ...       ...   
1624          Tera Mera Saath Rahen          Tera Mera Saath Rahen         0   
1625           Yeh Zindagi Ka Safar           Yeh Zindagi Ka Safar         0   
1626                Sabse Bada Sukh                Sabse Bada Sukh         0   
1627                          Daaka                          Daaka         0   
1628                       Humsafar                       Humsafar         0   

      year_of_release runtime            genres  imdb_rating  imdb_votes  \
0                2019     138  Action|Drama|War          8.4       35112   
1                2019     131               War          4.1          73   
2                2019     112   Biography|Drama          6.1        5549   
3                2019     121       Crime|Drama          6.0        1891   
4                2018     102             Drama          7.3         280   
...               ...     ...               ...          ...         ...   
1624             2001     148             Drama          4.9         278   
1625             2001     146             Drama          3.0         133   
1626             2018      \N      Comedy|Drama          6.1          13   
1627             2019     136            Action          7.4          38   
1628             2011      35     Drama|Romance          9.0        2968   

                                              

In [14]:
movies.head()

title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224   
1                         Battalion 609  tt9472208   
2  The Accidental Prime Minister (film)  tt6986710   
3                       Why Cheat India  tt8108208   
4                       Evening Shadows  tt6028796   

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                NaN   
2  https://upload.wikimedia.org/wikipedia/en/thum...   
3  https://upload.wikimedia.org/wikipedia/en/thum...   
4                                                NaN   

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1        https://en.wikipedia.org/wiki/Battalion_609   
2  https://en.wikipedia.org/wiki/The_Accidental_P...   
3      https://en.wikipedia.org/wiki/Why_Cheat_India   
4      https://en.wikipedia.org/wiki/Evening_Shadows   

                         title_y                 original_title  is_adult  \
0       Uri: The Surgical Strike       Uri: The Surgical Strike         0   
1                  Battalion 609                  Battalion 609         0   
2  The Accidental Prime Minister  The Accidental Prime Minister         0   
3                Why Cheat India                Why Cheat India         0   
4                Evening Shadows                Evening Shadows         0   

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112   
1             2019     131               War          4.1          73   
2             2019     112   Biography|Drama          6.1        5549   
3             2019     121       Crime|Drama          6.0        1891   
4             2018     102             Drama          7.3         280   

                                               story  \
0  Divided over five chapters  the film chronicle...   
1  The story revolves around a cricket match betw...   
2  Based on the memoir by Indian policy analyst S...   
3  The movie focuses on existing malpractices in ...   
4  While gay rights and marriage equality has bee...   

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN   
1  The story of Battalion 609 revolves around a c...     NaN   
2  Explores Manmohan Singh's tenure as the Prime ...     NaN   
3  The movie focuses on existing malpractices in ...     NaN   
4  Under the 'Evening Shadows'  truth often plays...     NaN   

                                              actors        wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...                  4 wins   
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...                     NaN   
2  Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...                     NaN   
3  Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...                     NaN   
4  Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...  17 wins & 1 nomination   

              release_date  
0    11 January 2019 (USA)  
1  11 January 2019 (India)  
2    11 January 2019 (USA)  
3    18 January 2019 (USA)  
4  11 January 2019 (India)

In [ ]:
ipl = pd.read_csv('ipl-matches.csv')
ipl

In [16]:
ipl.head()

ID       City        Date Season  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29   2022        Final   
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2   
2  1312198    Kolkata  2022-05-25   2022   Eliminator   
3  1312197    Kolkata  2022-05-24   2022  Qualifier 1   
4  1304116     Mumbai  2022-05-22   2022           70   

                         Team1                 Team2  \
0             Rajasthan Royals        Gujarat Titans   
1  Royal Challengers Bangalore      Rajasthan Royals   
2  Royal Challengers Bangalore  Lucknow Super Giants   
3             Rajasthan Royals        Gujarat Titans   
4          Sunrisers Hyderabad          Punjab Kings   

                              Venue            TossWinner TossDecision  \
0  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals          bat   
1  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals        field   
2             Eden Gardens, Kolkata  Lucknow Super Giants        field   
3             Eden Gardens, Kolkata        Gujarat Titans        field   
4          Wankhede Stadium, Mumbai   Sunrisers Hyderabad          bat   

  SuperOver                  WinningTeam    WonBy  Margin method  \
0         N               Gujarat Titans  Wickets     7.0    NaN   
1         N             Rajasthan Royals  Wickets     7.0    NaN   
2         N  Royal Challengers Bangalore     Runs    14.0    NaN   
3         N               Gujarat Titans  Wickets     7.0    NaN   
4         N                 Punjab Kings  Wickets     5.0    NaN   

  Player_of_Match                                       Team1Players  \
0       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
2      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
3       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
4   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...   

                                        Team2Players        Umpire1  \
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney   
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney   
2  ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal   
3  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford   
4  ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary   

         Umpire2  
0    Nitin Menon  
1    Nitin Menon  
2       MA Gough  
3      VK Sharma  
4  NA Patwardhan

In [22]:
movies.tail()

title_x     imdb_id  \
1624  Tera Mera Saath Rahen   tt0301250   
1625   Yeh Zindagi Ka Safar   tt0298607   
1626        Sabse Bada Sukh   tt0069204   
1627                  Daaka  tt10833860   
1628               Humsafar   tt2403201   

                                            poster_path  \
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...   
1625  https://upload.wikimedia.org/wikipedia/en/thum...   
1626                                                NaN   
1627  https://upload.wikimedia.org/wikipedia/en/thum...   
1628  https://upload.wikimedia.org/wikipedia/en/thum...   

                                              wiki_link  \
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...   
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...   
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh   
1627                https://en.wikipedia.org/wiki/Daaka   
1628             https://en.wikipedia.org/wiki/Humsafar   

                    title_y         original_title  is_adult  year_of_release  \
1624  Tera Mera Saath Rahen  Tera Mera Saath Rahen         0             2001   
1625   Yeh Zindagi Ka Safar   Yeh Zindagi Ka Safar         0             2001   
1626        Sabse Bada Sukh        Sabse Bada Sukh         0             2018   
1627                  Daaka                  Daaka         0             2019   
1628               Humsafar               Humsafar         0             2011   

     runtime         genres  imdb_rating  imdb_votes  \
1624     148          Drama          4.9         278   
1625     146          Drama          3.0         133   
1626      \N   Comedy|Drama          6.1          13   
1627     136         Action          7.4          38   
1628      35  Drama|Romance          9.0        2968   

                                                  story  \
1624  Raj Dixit lives with his younger brother  Rahu...   
1625  Hindi pop-star  Sarina Devan  lives a wealthy ...   
1626  Village born Lalloo re-locates to Bombay  and ...   
1627  Shinda tries robbing a bank so he can be wealt...   
1628  Sara and Ashar are childhood friends who share...   

                                                summary tagline  \
1624  A man is torn between his handicapped brother ...     NaN   
1625  A singer finds out she was adopted when the ed...     NaN   
1626  Village born Lalloo re-locates to Bombay  and ...     NaN   
1627  Shinda tries robbing a bank so he can be wealt...     NaN   
1628  Ashar and Khirad are forced to get married due...     NaN   

                                                 actors wins_nominations  \
1624  Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...              NaN   
1625  Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...              NaN   
1626  Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...              NaN   
1627                          Gippy Grewal|Zareen Khan|              NaN   
1628                                        Fawad Khan|              NaN   

                  release_date  
1624   7 November 2001 (India)  
1625  16 November 2001 (India)  
1626                       NaN  
1627     1 November 2019 (USA)  
1628     TV Series (2011–2012)

# DataFrame Attributes and Methods

In [20]:
# shape
print(movies.shape)
print(ipl.shape)

(1629, 18)
(950, 20)


In [21]:
# dtypes
ipl.dtypes

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [ ]:
movies.head(2)

In [ ]:
ipl.tail(2)


In [ ]:
# isnull
movies.isnull().sum()
ipl.isnull().sum()